name: Nexa API Integration Testing

on:
  push:
    branches:
      - main
  schedule:
    - cron: '15 14 * * 0,1,2,3,4,5'
    - cron: '30 5 * * 0,1,2,3,4,5'
  workflow_dispatch:
    inputs:
      XML_SUITE:
        description: "Path to testNG xml"
        default: "regression-suite.xml"
        required: false
      GROUPS:
        description: "Group(s) to run"
        default: "regression"
        required: true
      ENV:
        description: "Environment to run"
        default: "stage"
        required: true
        options:
          - stage
          - Prod
      UP_STREAM:
        description: "Upstream status"
        default: ""
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        id: build_maven
        working-directory: nexa_api-master  # Specify the directory where pom.xml exists
        run: |
          mvn clean test -DxmlSuite=${{ github.event.inputs.XML_SUITE }} -Dgroups=${{ github.event.inputs.GROUPS }} -Denv=${{ github.event.inputs.ENV }} | tee result.log
          percent=$(grep -oP '\d+(?=% Passed)' result.log || echo '0')
          echo "::set-output name=percent::$percent"

      - name: Validate Passed Rate
        if: ${{ github.event.inputs.UP_STREAM != '' }}
        uses: ./.github/actions/validate-dev-repo
        with:
          PERCENTAGE: ${{ steps.build_maven.outputs.percent }}
          SHA: ${{ github.sha }}
          REPO: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_TOKEN }}

      - name: Send notification to Slack (Success with 100% passed)
        if: success() && steps.build_maven.outputs.percent == '100'
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "channel": "slackintegrationnexa",
              "attachments": [
                {
                  "color": "good",
                  "title": "Nexa API Integration Testing",
                  "fields": [
                    {
                      "title": "Status",
                      "value": "Success",
                      "short": true
                    },
                    {
                      "title": "Passed Percentage",
                      "value": "100%",
                      "short": true
                    },
                    {
                      "title": "Branch",
                      "value": "${{ github.ref }}",
                      "short": true
                    },
                    {
                      "title": "Commit",
                      "value": "${{ github.sha }}",
                      "short": true
                    }
                  ],
                  "footer": "GitHub Actions",
                  "footer_icon": "https://github.githubassets.com/favicon.ico",
                  "ts": "$(date +%s)"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send notification to Slack (Failure or not 100% passed)
        if: failure() || steps.build_maven.outputs.percent != '100'
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "channel": "slackintegrationnexa",
              "attachments": [
                {
                  "color": "danger",
                  "title": "Nexa API Integration Testing",
                  "fields": [
                    {
                      "title": "Status",
                      "value": "${{ job.status }}",
                      "short": true
                    },
                    {
                      "title": "Passed Percentage",
                      "value": "${{ steps.build_maven.outputs.percent }}%",
                      "short": true
                    },
                    {
                      "title": "Branch",
                      "value": "${{ github.ref }}",
                      "short": true
                    },
                    {
                      "title": "Commit",
                      "value": "${{ github.sha }}",
                      "short": true
                    }
                  ],
                  "footer": "GitHub Actions",
                  "footer_icon": "https://github.githubassets.com/favicon.ico",
                  "ts": "$(date +%s)"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
