name: Nexa API Integration Testing
on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build and test with Maven
        run: mvn clean test TestNG.xml
