name: Nexa API Integration Testing
on:
  push:
    branches:
      - main
  schedule:
    - cron: '15 14 * * 0,1,2,3,4,5'
    - cron: '30 5 * * 0,1,2,3,4,5'
  workflow_dispatch:
    inputs:
      XML_SUITE:
        description: "Path to testNG xml"
        default: "regression-suite.xml"
        required: false
      GROUPS:
        description: "Group(s) to run"
        default: "regression"
        required: true
      ENV:
        description: "Environment to run"
        default: "stage"
        required: true
        options:
          - stage
          - Prod
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        working-directory: nexa_api-master  # Specify the directory where pom.xml exists
        run: |
          mvn clean test -DxmlSuite=${{ github.event.inputs.XML_SUITE }} -Dgroups=${{ github.event.inputs.GROUPS }} -Denv=${{ github.event.inputs.ENV }} | tee result.log
          echo "##vso[task.setvariable variable=percent]$(grep -oP '\d+(?=% Passed)' result.log || echo '0')"
      - name: Validate Passed Rate
        if: ${{ github.event.inputs.UP_STREAM != '' }}
        run: |
          echo "${{ env.percent }}% Passed Rate"
          # Add your validation logic here using the passed rate
          # Example: echo "$PERCENTAGE, $SHA, $REPO"
          # Assuming the validate-dev-repo action script usage
          # uses: ./.github/actions/validate-dev-repo
          # with:
          #   PERCENTAGE: ${{ env.percent }}
          #   SHA: ${{ github.sha }}
          #   REPO: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_TOKEN }}
- uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#workflows'
        if: always()
