name: Nexa API Integration Testing
on:
  push:
    branches:
      - main
  schedule:
    - cron: '15 14 * * 0,1,2,3,4,5'
    - cron: '30 5 * * 0,1,2,3,4,5'
  workflow_dispatch:
    inputs:
      XML_SUITE:
        type: string
        description: "Path to testNG xml"
        default: "regression-suite.xml"
        required: false
      GROUPS:
        type: string
        description: "Group(s) to run"
        default: "regression"
        required: true
      ENV:
        type: choice
        description: "Environment to run"
        options: ["Staging", "Dev"]
        default: "Staging"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        working-directory: nexa_api-master  # Specify the directory where pom.xml exists
        run: |
          mvn clean test -DsuiteXmlFile=TestNG.xml -DEnvironment=Stage -Dgroups=Sanity -DSheetName=Sanity
      - name: Parse Test Results
        id: test_results
        run: |
          total=$(awk '/Tests run:/ {print $3}' result.log | tail -1)
          failures=$(awk '/Failures:/ {print $6}' result.log | tail -1)
          errors=$(awk '/Errors:/ {print $8}' result.log | tail -1)
          skipped=$(awk '/Skipped:/ {print $10}' result.log | tail -1)
          passed=$((total - failures - errors - skipped))
          echo "total=$total" >> $GITHUB_ENV
          echo "passed=$passed" >> $GITHUB_ENV
          echo "failures=$failures" >> $GITHUB_ENV
          echo "skipped=$skipped" >> $GITHUB_ENV
      - name: Send Slack Notification
        if: always()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "Build job has finished for environment: ${{ github.event.inputs.ENV }}.\n\nResults:\nTotal: ${{ env.total }}\nPassed: ${{ env.passed }}\nFailures: ${{ env.failures }}\nSkipped: ${{ env.skipped }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
