name: Nexa API Integration Testing
on:
  push:
    branches:
      - main
  schedule:
    - cron: '15 14 * * 0,1,2,3,4,5'
    - cron: '30 5 * * 0,1,2,3,4,5'
  workflow_dispatch:
    inputs:
      XML_SUITE:
        type: string
        description: "Path to testNG xml"
        default: "regression-suite.xml"
        required: false
      GROUPS:
        type: choice
        description: "Group(s)"
        options: ["Sanity", "Regression"]
        default: "Sanity"
        required: true
      ENV:
        type: choice
        description: "Environment"
        options: ["Stage", "Prod"]
        default: "Stage"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        working-directory: nexa_api-master
        run: |
          mvn clean test -DsuiteXmlFile=TestNG.xml -DEnvironment=${{ github.event.inputs.ENV }} -Dgroups=${{ github.event.inputs.GROUPS }} -DSheetName=${{ github.event.inputs.GROUPS }}
      - name: List directory after build
        working-directory: nexa_api-master
        run: |
          ls -R
      - name: List files in surefire-reports_Testing
        run: |
          ls -R nexa_api-master/target/surefire-reports

      - name: Parse Test Results
        id: test_results
        run: |
          # Ensure xmllint is installed
          if ! command -v xmllint &> /dev/null; then
            echo "xmllint could not be found, installing..."
            sudo apt-get install -y libxml2-utils
          fi
          
          # Check if the file exists and has content
          if [ -f nexa_api-master/target/surefire-reports/testng-results.xml ]; then
            echo "Parsing testng-results.xml"
            total=$(xmllint --xpath "count(//test-method)" nexa_api-master/target/surefire-reports/testng-results.xml)
            failures=$(xmllint --xpath "count(//test-method[@status='FAIL'])" nexa_api-master/target/surefire-reports/testng-results.xml)
            skipped=$(xmllint --xpath "count(//test-method[@status='SKIP'])" nexa_api-master/target/surefire-reports/testng-results.xml)
            passed=$((total - failures - skipped))
            
            echo "total=$total" >> $GITHUB_ENV
            echo "passed=$passed" >> $GITHUB_ENV
            echo "failures=$failures" >> $GITHUB_ENV
            echo "skipped=$skipped" >> $GITHUB_ENV
            
            echo "Total: $total"
            echo "Passed: $passed"
            echo "Failures: $failures"
            echo "Skipped: $skipped"
          else
            echo "testng-results.xml not found or is empty"
            exit 1
          fi

      - name: Send Slack Notification
        if: always()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "Build job has finished for environment: \n\n Environment: ${{ github.event.inputs.ENV }} \nResults:\nTotal: ${{ env.total }}\nPassed: ${{ env.passed }}\nFailures: ${{ env.failures }}\nSkipped: ${{ env.skipped }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
