name: Nexa API Integration Testing
on:
  push:
    branches:
      - main
  schedule:
    - cron: '15 14 * * 0,1,2,3,4,5'
    - cron: '30 5 * * 0,1,2,3,4,5'
  workflow_dispatch:
    inputs:
      XML_SUITE:
        description: "Path to testNG xml"
        default: "regression-suite.xml"
        required: false
      GROUPS:
        description: "Group(s) to run"
        default: "regression"
        required: true
      ENV:
        description: "Environment to run"
        default: "stage"
        required: true
        options:
          - stage
          - Prod
      UP_STREAM:
        description: "Upstream dependency"
        required: false
      SLACK_WEBHOOK_URL:
        description: "Slack webhook URL"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        working-directory: nexa_api-master  # Specify the directory where pom.xml exists
        run: |
          mvn clean test -DxmlSuite=${{ github.event.inputs.XML_SUITE }} -Dgroups=${{ github.event.inputs.GROUPS }} -Denv=${{ github.event.inputs.ENV }} | tee result.log
      - name: Parse Test Results
        id: test_results
        run: |
          total=$(grep -oP '(?<=Tests run: )\d+' result.log | tail -1)
          passed=$(grep -oP '(?<=Tests run: \d+, Failures: 0, Errors: 0, Skipped: )\d+' result.log | tail -1)
          failed=$(grep -oP '(?<=Failures: )\d+' result.log | tail -1)
          skipped=$(grep -oP '(?<=Skipped: )\d+' result.log | tail -1)
          echo "::set-output name=total::$total"
          echo "::set-output name=passed::$passed"
          echo "::set-output name=failed::$failed"
          echo "::set-output name=skipped::$skipped"
      - name: Send Slack Notification
        if: always()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "Build job has finished for environment: ${{ github.event.inputs.ENV }}.",
              "attachments": [
                {
                  "color": "{{ job.status == 'success' ? 'good' : 'danger' }}",
                  "fields": [
                    {
                      "title": "Total Tests Run",
                      "value": "${{ steps.test_results.outputs.total }}",
                      "short": true
                    },
                    {
                      "title": "Passed",
                      "value": "${{ steps.test_results.outputs.passed }}",
                      "short": true
                    },
                    {
                      "title": "Failed",
                      "value": "${{ steps.test_results.outputs.failed }}",
                      "short": true
                    },
                    {
                      "title": "Skipped",
                      "value": "${{ steps.test_results.outputs.skipped }}",
                      "short": true
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
