name: hello-world-example
on:
  push:
schedule: ## Schedule the job to run at 9.30 am and 6.15pm Dubai time (All days except saturday).
    - cron: '15 14 * * 0,1,2,3,4,5'
    - cron: '30 5 * * 0,1,2,3,4,5'

workflow_dispatch:
    inputs:
      XML_SUITE:
        type: string
        description: "Path to testNG xml"
        default: "regression-suite.xml"
        required: false
      GROUPS:
        type: string
        description: "Group(s) to run"
        default: "regression"
        required: true
      RETRY_ENABLED:
        type: boolean
        description: "Enable retry"
        default: false
        required: false
      RETRY_COUNT:
        type: number
        description: "Number of retry"
        default: 1
        required: false
      UP_STREAM:
        type: string
        description: "Context from upstream repo, please send detail PR_NUMBER , REPO, SHA, ACTOR and URL of on-demand env"
        required: false
      ENV:
        type: choice
        description: "Environment to run"
        options: [ "staging", "dev" ]
        default: "staging"
        required: true

env:
  NAME: "CMS-Nexa"
  WEB_UI_GROUPS: "Stage"
  XML_SUITE: "TestNG.xml"
  ENV: "Stage"

jobs:
  build:
    runs-on: cms-web
    outputs:
      test_percentage: ${{ steps.test.outputs.percent }}
    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v3
